[features]
seeds = true
skip-lint = false
[programs.localnet]
my_awesome_app = "BAv1R7yGTcga43cjmsHMcZsXTsLTxdK4UT4nMg8qzhTh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/harshghodkar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
